name: control_gastos
description: Control de Gastos con filtro por rango de fechas

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  shared_preferences: ^2.2.2
  pdf: ^3.10.4
  path_provider: ^2.1.1
  google_fonts: ^6.1.0
  open_file: ^3.2.1
  fl_chart: ^0.63.0  # Para gráficos en la siguiente mejora
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
